//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentItServer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RENTIT21Entities : DbContext
    {
        public RENTIT21Entities()
            : base("name=RENTIT21Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<channels> channels { get; set; }
        public DbSet<comments> comments { get; set; }
        public DbSet<genres> genres { get; set; }
        public DbSet<trackplays> trackplays { get; set; }
        public DbSet<tracks> tracks { get; set; }
        public DbSet<users> users { get; set; }
        public DbSet<votes> votes { get; set; }
    }
}
