//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentItServer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RENTIT21Entities : DbContext
    {
        public RENTIT21Entities()
            : base("name=RENTIT21Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Channel> channels { get; set; }
        public DbSet<Comment> comments { get; set; }
        public DbSet<Genre> genres { get; set; }
        public DbSet<TrackPlay> trackplays { get; set; }
        public DbSet<Track> tracks { get; set; }
        public DbSet<User> users { get; set; }
        public DbSet<Vote> votes { get; set; }
    }
}
