//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentItServer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RENTIT21Entities : DbContext
    {
        public RENTIT21Entities()
            : base("name=RENTIT21Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<SMUbook> SMUbooks { get; set; }
        public DbSet<SMUrental> SMUrentals { get; set; }
        public DbSet<SMUuser> SMUusers { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<Channel> Channels { get; set; }
        public DbSet<Genre> Genres { get; set; }
        public DbSet<Track> Tracks { get; set; }
        public DbSet<Comment> Comments { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<Vote> Votes { get; set; }
        public DbSet<TrackPlay> TrackPlays { get; set; }
    }
}
