//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentItServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMUuser
    {
        public SMUuser()
        {
            this.SMUrentals = new HashSet<SMUrental>();
        }
    
        public int id { get; set; }
        public string email { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public int isAdmin { get; set; }
    
        public virtual ICollection<SMUrental> SMUrentals { get; set; }
    }
}
