//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentItServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Track
    {
        public Track()
        {
            this.trackplays = new HashSet<TrackPlay>();
            this.votes = new HashSet<Vote>();
        }
    
        public int id { get; set; }
        public int channelId { get; set; }
        public string trackpath { get; set; }
        public string name { get; set; }
        public string artist { get; set; }
        public string length { get; set; }
        public Nullable<int> upvotes { get; set; }
        public Nullable<int> downvotes { get; set; }
    
        public virtual Channel channels { get; set; }
        public virtual ICollection<TrackPlay> trackplays { get; set; }
        public virtual ICollection<Vote> votes { get; set; }
    }
}
