//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentItServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrackPlay
    {
        public int trackId { get; set; }
        public System.DateTime date { get; set; }
        public System.DateTime playtime { get; set; }
    
        public virtual Track tracks { get; set; }
    }
}
