//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentItServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Comments = new HashSet<Comment>();
            this.Channels = new HashSet<Channel>();
            this.SubscribedChannels = new HashSet<Channel>();
            this.Votes = new HashSet<Vote>();
        }
    
        public int Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Channel> Channels { get; set; }
        public virtual ICollection<Channel> SubscribedChannels { get; set; }
        public virtual ICollection<Vote> Votes { get; set; }
    }
}
