//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentItServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.channels = new HashSet<Channel>();
            this.comments = new HashSet<Comment>();
            this.votes = new HashSet<Vote>();
        }
    
        public int id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
    
        public virtual ICollection<Channel> channels { get; set; }
        public virtual ICollection<Comment> comments { get; set; }
        public virtual ICollection<Vote> votes { get; set; }
        public virtual Channel channelsSubscriped { get; set; }
    }
}
