//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapAsp {
    
    
    public partial class Index {
        
        /// <summary>
        /// uc_streamPlayer control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BootstrapAsp.StreamPlayer uc_streamPlayer;
        
        /// <summary>
        /// StreamPlayer1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BootstrapAsp.StreamPlayer StreamPlayer1;
        
        /// <summary>
        /// StreamPlayer2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BootstrapAsp.StreamPlayer StreamPlayer2;
    }
}
