//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentItServer_UnitTests
{
    using System;
    using System.Collections.Generic;
    
    public partial class Track
    {
        public Track()
        {
            this.TrackPlays = new HashSet<TrackPlay>();
            this.Votes = new HashSet<Vote>();
        }
    
        public int Id { get; set; }
        public int ChannelId { get; set; }
        public string Path { get; set; }
        public string Name { get; set; }
        public string Artist { get; set; }
        public int Length { get; set; }
        public int UpVotes { get; set; }
        public int DownVotes { get; set; }
    
        public virtual Channel Channel { get; set; }
        public virtual ICollection<TrackPlay> TrackPlays { get; set; }
        public virtual ICollection<Vote> Votes { get; set; }
    }
}
