//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentItMvc.RentItService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/RentItServer.ITU.DatabaseWrapperObjects")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Channel", Namespace="http://schemas.datacontract.org/2004/07/RentItServer.ITU.DatabaseWrapperObjects")]
    [System.SerializableAttribute()]
    public partial class Channel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] GenresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> HitsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OwnerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> RatingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreamUriField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Genres {
            get {
                return this.GenresField;
            }
            set {
                if ((object.ReferenceEquals(this.GenresField, value) != true)) {
                    this.GenresField = value;
                    this.RaisePropertyChanged("Genres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Hits {
            get {
                return this.HitsField;
            }
            set {
                if ((this.HitsField.Equals(value) != true)) {
                    this.HitsField = value;
                    this.RaisePropertyChanged("Hits");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OwnerId {
            get {
                return this.OwnerIdField;
            }
            set {
                if ((this.OwnerIdField.Equals(value) != true)) {
                    this.OwnerIdField = value;
                    this.RaisePropertyChanged("OwnerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Rating {
            get {
                return this.RatingField;
            }
            set {
                if ((this.RatingField.Equals(value) != true)) {
                    this.RatingField = value;
                    this.RaisePropertyChanged("Rating");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StreamUri {
            get {
                return this.StreamUriField;
            }
            set {
                if ((object.ReferenceEquals(this.StreamUriField, value) != true)) {
                    this.StreamUriField = value;
                    this.RaisePropertyChanged("StreamUri");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChannelSearchArgs", Namespace="http://schemas.datacontract.org/2004/07/RentItServer.ITU")]
    [System.SerializableAttribute()]
    public partial class ChannelSearchArgs : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AmountPlayedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EndIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] GenresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HitsAscField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HitsDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameAscField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberOfCommentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumberOfCommentsAscField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumberOfCommentsDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberOfSubscriptionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double RatingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RatingAscField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RatingDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SearchStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SortOptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StartIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubscriptionsAscField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubscriptionsDescField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AmountPlayed {
            get {
                return this.AmountPlayedField;
            }
            set {
                if ((this.AmountPlayedField.Equals(value) != true)) {
                    this.AmountPlayedField = value;
                    this.RaisePropertyChanged("AmountPlayed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EndIndex {
            get {
                return this.EndIndexField;
            }
            set {
                if ((this.EndIndexField.Equals(value) != true)) {
                    this.EndIndexField = value;
                    this.RaisePropertyChanged("EndIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Genres {
            get {
                return this.GenresField;
            }
            set {
                if ((object.ReferenceEquals(this.GenresField, value) != true)) {
                    this.GenresField = value;
                    this.RaisePropertyChanged("Genres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HitsAsc {
            get {
                return this.HitsAscField;
            }
            set {
                if ((object.ReferenceEquals(this.HitsAscField, value) != true)) {
                    this.HitsAscField = value;
                    this.RaisePropertyChanged("HitsAsc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HitsDesc {
            get {
                return this.HitsDescField;
            }
            set {
                if ((object.ReferenceEquals(this.HitsDescField, value) != true)) {
                    this.HitsDescField = value;
                    this.RaisePropertyChanged("HitsDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameAsc {
            get {
                return this.NameAscField;
            }
            set {
                if ((object.ReferenceEquals(this.NameAscField, value) != true)) {
                    this.NameAscField = value;
                    this.RaisePropertyChanged("NameAsc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameDesc {
            get {
                return this.NameDescField;
            }
            set {
                if ((object.ReferenceEquals(this.NameDescField, value) != true)) {
                    this.NameDescField = value;
                    this.RaisePropertyChanged("NameDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumberOfComments {
            get {
                return this.NumberOfCommentsField;
            }
            set {
                if ((this.NumberOfCommentsField.Equals(value) != true)) {
                    this.NumberOfCommentsField = value;
                    this.RaisePropertyChanged("NumberOfComments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumberOfCommentsAsc {
            get {
                return this.NumberOfCommentsAscField;
            }
            set {
                if ((object.ReferenceEquals(this.NumberOfCommentsAscField, value) != true)) {
                    this.NumberOfCommentsAscField = value;
                    this.RaisePropertyChanged("NumberOfCommentsAsc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumberOfCommentsDesc {
            get {
                return this.NumberOfCommentsDescField;
            }
            set {
                if ((object.ReferenceEquals(this.NumberOfCommentsDescField, value) != true)) {
                    this.NumberOfCommentsDescField = value;
                    this.RaisePropertyChanged("NumberOfCommentsDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumberOfSubscriptions {
            get {
                return this.NumberOfSubscriptionsField;
            }
            set {
                if ((this.NumberOfSubscriptionsField.Equals(value) != true)) {
                    this.NumberOfSubscriptionsField = value;
                    this.RaisePropertyChanged("NumberOfSubscriptions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Rating {
            get {
                return this.RatingField;
            }
            set {
                if ((this.RatingField.Equals(value) != true)) {
                    this.RatingField = value;
                    this.RaisePropertyChanged("Rating");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RatingAsc {
            get {
                return this.RatingAscField;
            }
            set {
                if ((object.ReferenceEquals(this.RatingAscField, value) != true)) {
                    this.RatingAscField = value;
                    this.RaisePropertyChanged("RatingAsc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RatingDesc {
            get {
                return this.RatingDescField;
            }
            set {
                if ((object.ReferenceEquals(this.RatingDescField, value) != true)) {
                    this.RatingDescField = value;
                    this.RaisePropertyChanged("RatingDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SearchString {
            get {
                return this.SearchStringField;
            }
            set {
                if ((object.ReferenceEquals(this.SearchStringField, value) != true)) {
                    this.SearchStringField = value;
                    this.RaisePropertyChanged("SearchString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SortOption {
            get {
                return this.SortOptionField;
            }
            set {
                if ((object.ReferenceEquals(this.SortOptionField, value) != true)) {
                    this.SortOptionField = value;
                    this.RaisePropertyChanged("SortOption");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StartIndex {
            get {
                return this.StartIndexField;
            }
            set {
                if ((this.StartIndexField.Equals(value) != true)) {
                    this.StartIndexField = value;
                    this.RaisePropertyChanged("StartIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubscriptionsAsc {
            get {
                return this.SubscriptionsAscField;
            }
            set {
                if ((object.ReferenceEquals(this.SubscriptionsAscField, value) != true)) {
                    this.SubscriptionsAscField = value;
                    this.RaisePropertyChanged("SubscriptionsAsc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubscriptionsDesc {
            get {
                return this.SubscriptionsDescField;
            }
            set {
                if ((object.ReferenceEquals(this.SubscriptionsDescField, value) != true)) {
                    this.SubscriptionsDescField = value;
                    this.RaisePropertyChanged("SubscriptionsDesc");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Track", Namespace="http://schemas.datacontract.org/2004/07/RentItServer.ITU.DatabaseWrapperObjects")]
    [System.SerializableAttribute()]
    public partial class Track : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArtistField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ChannelIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DownVotesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LengthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UpVotesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Artist {
            get {
                return this.ArtistField;
            }
            set {
                if ((object.ReferenceEquals(this.ArtistField, value) != true)) {
                    this.ArtistField = value;
                    this.RaisePropertyChanged("Artist");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ChannelId {
            get {
                return this.ChannelIdField;
            }
            set {
                if ((this.ChannelIdField.Equals(value) != true)) {
                    this.ChannelIdField = value;
                    this.RaisePropertyChanged("ChannelId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DownVotes {
            get {
                return this.DownVotesField;
            }
            set {
                if ((this.DownVotesField.Equals(value) != true)) {
                    this.DownVotesField = value;
                    this.RaisePropertyChanged("DownVotes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Length {
            get {
                return this.LengthField;
            }
            set {
                if ((this.LengthField.Equals(value) != true)) {
                    this.LengthField = value;
                    this.RaisePropertyChanged("Length");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Path {
            get {
                return this.PathField;
            }
            set {
                if ((object.ReferenceEquals(this.PathField, value) != true)) {
                    this.PathField = value;
                    this.RaisePropertyChanged("Path");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UpVotes {
            get {
                return this.UpVotesField;
            }
            set {
                if ((this.UpVotesField.Equals(value) != true)) {
                    this.UpVotesField = value;
                    this.RaisePropertyChanged("UpVotes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Comment", Namespace="http://schemas.datacontract.org/2004/07/RentItServer.ITU.DatabaseWrapperObjects")]
    [System.SerializableAttribute()]
    public partial class Comment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ChannelIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime PostTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ChannelId {
            get {
                return this.ChannelIdField;
            }
            set {
                if ((this.ChannelIdField.Equals(value) != true)) {
                    this.ChannelIdField = value;
                    this.RaisePropertyChanged("ChannelId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PostTime {
            get {
                return this.PostTimeField;
            }
            set {
                if ((this.PostTimeField.Equals(value) != true)) {
                    this.PostTimeField = value;
                    this.RaisePropertyChanged("PostTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vote", Namespace="http://schemas.datacontract.org/2004/07/RentItServer.ITU.DatabaseWrapperObjects")]
    [System.SerializableAttribute()]
    public partial class Vote : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TrackIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime VoteTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TrackId {
            get {
                return this.TrackIdField;
            }
            set {
                if ((this.TrackIdField.Equals(value) != true)) {
                    this.TrackIdField = value;
                    this.RaisePropertyChanged("TrackId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime VoteTime {
            get {
                return this.VoteTimeField;
            }
            set {
                if ((this.VoteTimeField.Equals(value) != true)) {
                    this.VoteTimeField = value;
                    this.RaisePropertyChanged("VoteTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TrackSearchArgs", Namespace="http://schemas.datacontract.org/2004/07/RentItServer.ITU")]
    [System.SerializableAttribute()]
    public partial class TrackSearchArgs : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArtistField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArtistAscField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArtistDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DownvotesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DownvotesAscField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DownvotesDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EndIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameAscField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SearchStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SortOptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StartIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UpvotesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpvotesAscField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpvotesDescField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Artist {
            get {
                return this.ArtistField;
            }
            set {
                if ((object.ReferenceEquals(this.ArtistField, value) != true)) {
                    this.ArtistField = value;
                    this.RaisePropertyChanged("Artist");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ArtistAsc {
            get {
                return this.ArtistAscField;
            }
            set {
                if ((object.ReferenceEquals(this.ArtistAscField, value) != true)) {
                    this.ArtistAscField = value;
                    this.RaisePropertyChanged("ArtistAsc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ArtistDesc {
            get {
                return this.ArtistDescField;
            }
            set {
                if ((object.ReferenceEquals(this.ArtistDescField, value) != true)) {
                    this.ArtistDescField = value;
                    this.RaisePropertyChanged("ArtistDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Downvotes {
            get {
                return this.DownvotesField;
            }
            set {
                if ((this.DownvotesField.Equals(value) != true)) {
                    this.DownvotesField = value;
                    this.RaisePropertyChanged("Downvotes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DownvotesAsc {
            get {
                return this.DownvotesAscField;
            }
            set {
                if ((object.ReferenceEquals(this.DownvotesAscField, value) != true)) {
                    this.DownvotesAscField = value;
                    this.RaisePropertyChanged("DownvotesAsc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DownvotesDesc {
            get {
                return this.DownvotesDescField;
            }
            set {
                if ((object.ReferenceEquals(this.DownvotesDescField, value) != true)) {
                    this.DownvotesDescField = value;
                    this.RaisePropertyChanged("DownvotesDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EndIndex {
            get {
                return this.EndIndexField;
            }
            set {
                if ((this.EndIndexField.Equals(value) != true)) {
                    this.EndIndexField = value;
                    this.RaisePropertyChanged("EndIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameAsc {
            get {
                return this.NameAscField;
            }
            set {
                if ((object.ReferenceEquals(this.NameAscField, value) != true)) {
                    this.NameAscField = value;
                    this.RaisePropertyChanged("NameAsc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameDesc {
            get {
                return this.NameDescField;
            }
            set {
                if ((object.ReferenceEquals(this.NameDescField, value) != true)) {
                    this.NameDescField = value;
                    this.RaisePropertyChanged("NameDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SearchString {
            get {
                return this.SearchStringField;
            }
            set {
                if ((object.ReferenceEquals(this.SearchStringField, value) != true)) {
                    this.SearchStringField = value;
                    this.RaisePropertyChanged("SearchString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SortOption {
            get {
                return this.SortOptionField;
            }
            set {
                if ((object.ReferenceEquals(this.SortOptionField, value) != true)) {
                    this.SortOptionField = value;
                    this.RaisePropertyChanged("SortOption");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StartIndex {
            get {
                return this.StartIndexField;
            }
            set {
                if ((this.StartIndexField.Equals(value) != true)) {
                    this.StartIndexField = value;
                    this.RaisePropertyChanged("StartIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Upvotes {
            get {
                return this.UpvotesField;
            }
            set {
                if ((this.UpvotesField.Equals(value) != true)) {
                    this.UpvotesField = value;
                    this.RaisePropertyChanged("Upvotes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UpvotesAsc {
            get {
                return this.UpvotesAscField;
            }
            set {
                if ((object.ReferenceEquals(this.UpvotesAscField, value) != true)) {
                    this.UpvotesAscField = value;
                    this.RaisePropertyChanged("UpvotesAsc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UpvotesDesc {
            get {
                return this.UpvotesDescField;
            }
            set {
                if ((object.ReferenceEquals(this.UpvotesDescField, value) != true)) {
                    this.UpvotesDescField = value;
                    this.RaisePropertyChanged("UpvotesDesc");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RentItService.IRentItService")]
    public interface IRentItService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/Login", ReplyAction="http://tempuri.org/IRentItService/LoginResponse")]
        RentItMvc.RentItService.User Login(string usernameOrEmail, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/Login", ReplyAction="http://tempuri.org/IRentItService/LoginResponse")]
        System.Threading.Tasks.Task<RentItMvc.RentItService.User> LoginAsync(string usernameOrEmail, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/SignUp", ReplyAction="http://tempuri.org/IRentItService/SignUpResponse")]
        RentItMvc.RentItService.User SignUp(string usernameOrEmail, string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/SignUp", ReplyAction="http://tempuri.org/IRentItService/SignUpResponse")]
        System.Threading.Tasks.Task<RentItMvc.RentItService.User> SignUpAsync(string usernameOrEmail, string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/DeleteUser", ReplyAction="http://tempuri.org/IRentItService/DeleteUserResponse")]
        void DeleteUser(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/DeleteUser", ReplyAction="http://tempuri.org/IRentItService/DeleteUserResponse")]
        System.Threading.Tasks.Task DeleteUserAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/GetUser", ReplyAction="http://tempuri.org/IRentItService/GetUserResponse")]
        RentItMvc.RentItService.User GetUser(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/GetUser", ReplyAction="http://tempuri.org/IRentItService/GetUserResponse")]
        System.Threading.Tasks.Task<RentItMvc.RentItService.User> GetUserAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/IsCorrectPassword", ReplyAction="http://tempuri.org/IRentItService/IsCorrectPasswordResponse")]
        bool IsCorrectPassword(int userId, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/IsCorrectPassword", ReplyAction="http://tempuri.org/IRentItService/IsCorrectPasswordResponse")]
        System.Threading.Tasks.Task<bool> IsCorrectPasswordAsync(int userId, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/GetAllUserIds", ReplyAction="http://tempuri.org/IRentItService/GetAllUserIdsResponse")]
        int[] GetAllUserIds();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/GetAllUserIds", ReplyAction="http://tempuri.org/IRentItService/GetAllUserIdsResponse")]
        System.Threading.Tasks.Task<int[]> GetAllUserIdsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/UpdateUser", ReplyAction="http://tempuri.org/IRentItService/UpdateUserResponse")]
        void UpdateUser(int userId, string username, string password, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/UpdateUser", ReplyAction="http://tempuri.org/IRentItService/UpdateUserResponse")]
        System.Threading.Tasks.Task UpdateUserAsync(int userId, string username, string password, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/CreateChannel", ReplyAction="http://tempuri.org/IRentItService/CreateChannelResponse")]
        int CreateChannel(string channelName, int userId, string description, string[] genres);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/CreateChannel", ReplyAction="http://tempuri.org/IRentItService/CreateChannelResponse")]
        System.Threading.Tasks.Task<int> CreateChannelAsync(string channelName, int userId, string description, string[] genres);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/DeleteChannel", ReplyAction="http://tempuri.org/IRentItService/DeleteChannelResponse")]
        void DeleteChannel(int channelId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/DeleteChannel", ReplyAction="http://tempuri.org/IRentItService/DeleteChannelResponse")]
        System.Threading.Tasks.Task DeleteChannelAsync(int channelId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/UpdateChannel", ReplyAction="http://tempuri.org/IRentItService/UpdateChannelResponse")]
        void UpdateChannel(int channelId, System.Nullable<int> ownerId, string channelName, string description, System.Nullable<double> hits, System.Nullable<double> rating);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/UpdateChannel", ReplyAction="http://tempuri.org/IRentItService/UpdateChannelResponse")]
        System.Threading.Tasks.Task UpdateChannelAsync(int channelId, System.Nullable<int> ownerId, string channelName, string description, System.Nullable<double> hits, System.Nullable<double> rating);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/IncrementHitsForChannel", ReplyAction="http://tempuri.org/IRentItService/IncrementHitsForChannelResponse")]
        void IncrementHitsForChannel(int channelId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/IncrementHitsForChannel", ReplyAction="http://tempuri.org/IRentItService/IncrementHitsForChannelResponse")]
        System.Threading.Tasks.Task IncrementHitsForChannelAsync(int channelId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/GetChannel", ReplyAction="http://tempuri.org/IRentItService/GetChannelResponse")]
        RentItMvc.RentItService.Channel GetChannel(int channelId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/GetChannel", ReplyAction="http://tempuri.org/IRentItService/GetChannelResponse")]
        System.Threading.Tasks.Task<RentItMvc.RentItService.Channel> GetChannelAsync(int channelId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/GetAllChannelIds", ReplyAction="http://tempuri.org/IRentItService/GetAllChannelIdsResponse")]
        int[] GetAllChannelIds();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/GetAllChannelIds", ReplyAction="http://tempuri.org/IRentItService/GetAllChannelIdsResponse")]
        System.Threading.Tasks.Task<int[]> GetAllChannelIdsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/GetChannels", ReplyAction="http://tempuri.org/IRentItService/GetChannelsResponse")]
        RentItMvc.RentItService.Channel[] GetChannels(RentItMvc.RentItService.ChannelSearchArgs args);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/GetChannels", ReplyAction="http://tempuri.org/IRentItService/GetChannelsResponse")]
        System.Threading.Tasks.Task<RentItMvc.RentItService.Channel[]> GetChannelsAsync(RentItMvc.RentItService.ChannelSearchArgs args);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/CreateVote", ReplyAction="http://tempuri.org/IRentItService/CreateVoteResponse")]
        void CreateVote(int rating, int userId, int trackId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/CreateVote", ReplyAction="http://tempuri.org/IRentItService/CreateVoteResponse")]
        System.Threading.Tasks.Task CreateVoteAsync(int rating, int userId, int trackId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/AddTrack", ReplyAction="http://tempuri.org/IRentItService/AddTrackResponse")]
        void AddTrack(int userId, int channelId, System.IO.MemoryStream audioStream);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/AddTrack", ReplyAction="http://tempuri.org/IRentItService/AddTrackResponse")]
        System.Threading.Tasks.Task AddTrackAsync(int userId, int channelId, System.IO.MemoryStream audioStream);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/GetTrackInfoByTrackname", ReplyAction="http://tempuri.org/IRentItService/GetTrackInfoByTracknameResponse")]
        RentItMvc.RentItService.Track GetTrackInfoByTrackname(int channelId, string trackname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/GetTrackInfoByTrackname", ReplyAction="http://tempuri.org/IRentItService/GetTrackInfoByTracknameResponse")]
        System.Threading.Tasks.Task<RentItMvc.RentItService.Track> GetTrackInfoByTracknameAsync(int channelId, string trackname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/RemoveTrack", ReplyAction="http://tempuri.org/IRentItService/RemoveTrackResponse")]
        void RemoveTrack(int trackId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/RemoveTrack", ReplyAction="http://tempuri.org/IRentItService/RemoveTrackResponse")]
        System.Threading.Tasks.Task RemoveTrackAsync(int trackId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/GetTrackIds", ReplyAction="http://tempuri.org/IRentItService/GetTrackIdsResponse")]
        int[] GetTrackIds(int channelId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/GetTrackIds", ReplyAction="http://tempuri.org/IRentItService/GetTrackIdsResponse")]
        System.Threading.Tasks.Task<int[]> GetTrackIdsAsync(int channelId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/GetTracks", ReplyAction="http://tempuri.org/IRentItService/GetTracksResponse")]
        RentItMvc.RentItService.Track[] GetTracks(int channelId, RentItMvc.RentItService.TrackSearchArgs args);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/GetTracks", ReplyAction="http://tempuri.org/IRentItService/GetTracksResponse")]
        System.Threading.Tasks.Task<RentItMvc.RentItService.Track[]> GetTracksAsync(int channelId, RentItMvc.RentItService.TrackSearchArgs args);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/CreateComment", ReplyAction="http://tempuri.org/IRentItService/CreateCommentResponse")]
        void CreateComment(string comment, int userId, int channelId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/CreateComment", ReplyAction="http://tempuri.org/IRentItService/CreateCommentResponse")]
        System.Threading.Tasks.Task CreateCommentAsync(string comment, int userId, int channelId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/DeleteComment", ReplyAction="http://tempuri.org/IRentItService/DeleteCommentResponse")]
        void DeleteComment(int channelId, int userId, System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/DeleteComment", ReplyAction="http://tempuri.org/IRentItService/DeleteCommentResponse")]
        System.Threading.Tasks.Task DeleteCommentAsync(int channelId, int userId, System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/GetChannelComments", ReplyAction="http://tempuri.org/IRentItService/GetChannelCommentsResponse")]
        RentItMvc.RentItService.Comment[] GetChannelComments(int channelId, System.Nullable<int> fromInclusive, System.Nullable<int> toExclusive);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/GetChannelComments", ReplyAction="http://tempuri.org/IRentItService/GetChannelCommentsResponse")]
        System.Threading.Tasks.Task<RentItMvc.RentItService.Comment[]> GetChannelCommentsAsync(int channelId, System.Nullable<int> fromInclusive, System.Nullable<int> toExclusive);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/GetUserComments", ReplyAction="http://tempuri.org/IRentItService/GetUserCommentsResponse")]
        RentItMvc.RentItService.Comment[] GetUserComments(int userId, int fromInclusive, int toExclusive);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/GetUserComments", ReplyAction="http://tempuri.org/IRentItService/GetUserCommentsResponse")]
        System.Threading.Tasks.Task<RentItMvc.RentItService.Comment[]> GetUserCommentsAsync(int userId, int fromInclusive, int toExclusive);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/IsEmailAvailable", ReplyAction="http://tempuri.org/IRentItService/IsEmailAvailableResponse")]
        bool IsEmailAvailable(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/IsEmailAvailable", ReplyAction="http://tempuri.org/IRentItService/IsEmailAvailableResponse")]
        System.Threading.Tasks.Task<bool> IsEmailAvailableAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/IsUsernameAvailable", ReplyAction="http://tempuri.org/IRentItService/IsUsernameAvailableResponse")]
        bool IsUsernameAvailable(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/IsUsernameAvailable", ReplyAction="http://tempuri.org/IRentItService/IsUsernameAvailableResponse")]
        System.Threading.Tasks.Task<bool> IsUsernameAvailableAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/Subscribe", ReplyAction="http://tempuri.org/IRentItService/SubscribeResponse")]
        void Subscribe(int userId, int channelId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/Subscribe", ReplyAction="http://tempuri.org/IRentItService/SubscribeResponse")]
        System.Threading.Tasks.Task SubscribeAsync(int userId, int channelId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/Unsubscribe", ReplyAction="http://tempuri.org/IRentItService/UnsubscribeResponse")]
        void Unsubscribe(int userId, int channelId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/Unsubscribe", ReplyAction="http://tempuri.org/IRentItService/UnsubscribeResponse")]
        System.Threading.Tasks.Task UnsubscribeAsync(int userId, int channelId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/GetChannelPort", ReplyAction="http://tempuri.org/IRentItService/GetChannelPortResponse")]
        int GetChannelPort(int channelId, int ipAddress, int port);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/GetChannelPort", ReplyAction="http://tempuri.org/IRentItService/GetChannelPortResponse")]
        System.Threading.Tasks.Task<int> GetChannelPortAsync(int channelId, int ipAddress, int port);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/StartChannelStream", ReplyAction="http://tempuri.org/IRentItService/StartChannelStreamResponse")]
        void StartChannelStream(int cId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/StartChannelStream", ReplyAction="http://tempuri.org/IRentItService/StartChannelStreamResponse")]
        System.Threading.Tasks.Task StartChannelStreamAsync(int cId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/GetDefaultChannelSearchArgs", ReplyAction="http://tempuri.org/IRentItService/GetDefaultChannelSearchArgsResponse")]
        RentItMvc.RentItService.ChannelSearchArgs GetDefaultChannelSearchArgs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/GetDefaultChannelSearchArgs", ReplyAction="http://tempuri.org/IRentItService/GetDefaultChannelSearchArgsResponse")]
        System.Threading.Tasks.Task<RentItMvc.RentItService.ChannelSearchArgs> GetDefaultChannelSearchArgsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/GetDefaultTrackSearchArgs", ReplyAction="http://tempuri.org/IRentItService/GetDefaultTrackSearchArgsResponse")]
        RentItMvc.RentItService.TrackSearchArgs GetDefaultTrackSearchArgs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/GetDefaultTrackSearchArgs", ReplyAction="http://tempuri.org/IRentItService/GetDefaultTrackSearchArgsResponse")]
        System.Threading.Tasks.Task<RentItMvc.RentItService.TrackSearchArgs> GetDefaultTrackSearchArgsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/GetCreatedChannels", ReplyAction="http://tempuri.org/IRentItService/GetCreatedChannelsResponse")]
        RentItMvc.RentItService.Channel[] GetCreatedChannels(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/GetCreatedChannels", ReplyAction="http://tempuri.org/IRentItService/GetCreatedChannelsResponse")]
        System.Threading.Tasks.Task<RentItMvc.RentItService.Channel[]> GetCreatedChannelsAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/GetSubscribedChannels", ReplyAction="http://tempuri.org/IRentItService/GetSubscribedChannelsResponse")]
        RentItMvc.RentItService.Channel[] GetSubscribedChannels(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/GetSubscribedChannels", ReplyAction="http://tempuri.org/IRentItService/GetSubscribedChannelsResponse")]
        System.Threading.Tasks.Task<RentItMvc.RentItService.Channel[]> GetSubscribedChannelsAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/GetTrackByChannelId", ReplyAction="http://tempuri.org/IRentItService/GetTrackByChannelIdResponse")]
        RentItMvc.RentItService.Track[] GetTrackByChannelId(int channelId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/GetTrackByChannelId", ReplyAction="http://tempuri.org/IRentItService/GetTrackByChannelIdResponse")]
        System.Threading.Tasks.Task<RentItMvc.RentItService.Track[]> GetTrackByChannelIdAsync(int channelId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/GetRecentlyPlayedTracks", ReplyAction="http://tempuri.org/IRentItService/GetRecentlyPlayedTracksResponse")]
        RentItMvc.RentItService.Track[] GetRecentlyPlayedTracks(int channelId, int numberOfTracks);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/GetRecentlyPlayedTracks", ReplyAction="http://tempuri.org/IRentItService/GetRecentlyPlayedTracksResponse")]
        System.Threading.Tasks.Task<RentItMvc.RentItService.Track[]> GetRecentlyPlayedTracksAsync(int channelId, int numberOfTracks);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/IsChannelNameAvailable", ReplyAction="http://tempuri.org/IRentItService/IsChannelNameAvailableResponse")]
        bool IsChannelNameAvailable(int channelId, string channelName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/IsChannelNameAvailable", ReplyAction="http://tempuri.org/IRentItService/IsChannelNameAvailableResponse")]
        System.Threading.Tasks.Task<bool> IsChannelNameAvailableAsync(int channelId, string channelName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/GetSubscriberCount", ReplyAction="http://tempuri.org/IRentItService/GetSubscriberCountResponse")]
        int GetSubscriberCount(int channelId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/GetSubscriberCount", ReplyAction="http://tempuri.org/IRentItService/GetSubscriberCountResponse")]
        System.Threading.Tasks.Task<int> GetSubscriberCountAsync(int channelId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/IncrementChannelPlays", ReplyAction="http://tempuri.org/IRentItService/IncrementChannelPlaysResponse")]
        void IncrementChannelPlays(int channelId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/IncrementChannelPlays", ReplyAction="http://tempuri.org/IRentItService/IncrementChannelPlaysResponse")]
        System.Threading.Tasks.Task IncrementChannelPlaysAsync(int channelId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/IsChannelPlaying", ReplyAction="http://tempuri.org/IRentItService/IsChannelPlayingResponse")]
        bool IsChannelPlaying(int channelId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/IsChannelPlaying", ReplyAction="http://tempuri.org/IRentItService/IsChannelPlayingResponse")]
        System.Threading.Tasks.Task<bool> IsChannelPlayingAsync(int channelId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/StopChannelStream", ReplyAction="http://tempuri.org/IRentItService/StopChannelStreamResponse")]
        void StopChannelStream(int channelId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/StopChannelStream", ReplyAction="http://tempuri.org/IRentItService/StopChannelStreamResponse")]
        System.Threading.Tasks.Task StopChannelStreamAsync(int channelId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/GetVote", ReplyAction="http://tempuri.org/IRentItService/GetVoteResponse")]
        RentItMvc.RentItService.Vote GetVote(int userId, int trackId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/GetVote", ReplyAction="http://tempuri.org/IRentItService/GetVoteResponse")]
        System.Threading.Tasks.Task<RentItMvc.RentItService.Vote> GetVoteAsync(int userId, int trackId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/DeleteVote", ReplyAction="http://tempuri.org/IRentItService/DeleteVoteResponse")]
        void DeleteVote(int userId, int trackId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/DeleteVote", ReplyAction="http://tempuri.org/IRentItService/DeleteVoteResponse")]
        System.Threading.Tasks.Task DeleteVoteAsync(int userId, int trackId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/CountAllChannelsWithFilter", ReplyAction="http://tempuri.org/IRentItService/CountAllChannelsWithFilterResponse")]
        int CountAllChannelsWithFilter(RentItMvc.RentItService.ChannelSearchArgs filter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItService/CountAllChannelsWithFilter", ReplyAction="http://tempuri.org/IRentItService/CountAllChannelsWithFilterResponse")]
        System.Threading.Tasks.Task<int> CountAllChannelsWithFilterAsync(RentItMvc.RentItService.ChannelSearchArgs filter);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRentItServiceChannel : RentItMvc.RentItService.IRentItService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RentItServiceClient : System.ServiceModel.ClientBase<RentItMvc.RentItService.IRentItService>, RentItMvc.RentItService.IRentItService {
        
        public RentItServiceClient() {
        }
        
        public RentItServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RentItServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RentItServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RentItServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public RentItMvc.RentItService.User Login(string usernameOrEmail, string password) {
            return base.Channel.Login(usernameOrEmail, password);
        }
        
        public System.Threading.Tasks.Task<RentItMvc.RentItService.User> LoginAsync(string usernameOrEmail, string password) {
            return base.Channel.LoginAsync(usernameOrEmail, password);
        }
        
        public RentItMvc.RentItService.User SignUp(string usernameOrEmail, string email, string password) {
            return base.Channel.SignUp(usernameOrEmail, email, password);
        }
        
        public System.Threading.Tasks.Task<RentItMvc.RentItService.User> SignUpAsync(string usernameOrEmail, string email, string password) {
            return base.Channel.SignUpAsync(usernameOrEmail, email, password);
        }
        
        public void DeleteUser(int userId) {
            base.Channel.DeleteUser(userId);
        }
        
        public System.Threading.Tasks.Task DeleteUserAsync(int userId) {
            return base.Channel.DeleteUserAsync(userId);
        }
        
        public RentItMvc.RentItService.User GetUser(int userId) {
            return base.Channel.GetUser(userId);
        }
        
        public System.Threading.Tasks.Task<RentItMvc.RentItService.User> GetUserAsync(int userId) {
            return base.Channel.GetUserAsync(userId);
        }
        
        public bool IsCorrectPassword(int userId, string password) {
            return base.Channel.IsCorrectPassword(userId, password);
        }
        
        public System.Threading.Tasks.Task<bool> IsCorrectPasswordAsync(int userId, string password) {
            return base.Channel.IsCorrectPasswordAsync(userId, password);
        }
        
        public int[] GetAllUserIds() {
            return base.Channel.GetAllUserIds();
        }
        
        public System.Threading.Tasks.Task<int[]> GetAllUserIdsAsync() {
            return base.Channel.GetAllUserIdsAsync();
        }
        
        public void UpdateUser(int userId, string username, string password, string email) {
            base.Channel.UpdateUser(userId, username, password, email);
        }
        
        public System.Threading.Tasks.Task UpdateUserAsync(int userId, string username, string password, string email) {
            return base.Channel.UpdateUserAsync(userId, username, password, email);
        }
        
        public int CreateChannel(string channelName, int userId, string description, string[] genres) {
            return base.Channel.CreateChannel(channelName, userId, description, genres);
        }
        
        public System.Threading.Tasks.Task<int> CreateChannelAsync(string channelName, int userId, string description, string[] genres) {
            return base.Channel.CreateChannelAsync(channelName, userId, description, genres);
        }
        
        public void DeleteChannel(int channelId) {
            base.Channel.DeleteChannel(channelId);
        }
        
        public System.Threading.Tasks.Task DeleteChannelAsync(int channelId) {
            return base.Channel.DeleteChannelAsync(channelId);
        }
        
        public void UpdateChannel(int channelId, System.Nullable<int> ownerId, string channelName, string description, System.Nullable<double> hits, System.Nullable<double> rating) {
            base.Channel.UpdateChannel(channelId, ownerId, channelName, description, hits, rating);
        }
        
        public System.Threading.Tasks.Task UpdateChannelAsync(int channelId, System.Nullable<int> ownerId, string channelName, string description, System.Nullable<double> hits, System.Nullable<double> rating) {
            return base.Channel.UpdateChannelAsync(channelId, ownerId, channelName, description, hits, rating);
        }
        
        public void IncrementHitsForChannel(int channelId) {
            base.Channel.IncrementHitsForChannel(channelId);
        }
        
        public System.Threading.Tasks.Task IncrementHitsForChannelAsync(int channelId) {
            return base.Channel.IncrementHitsForChannelAsync(channelId);
        }
        
        public RentItMvc.RentItService.Channel GetChannel(int channelId) {
            return base.Channel.GetChannel(channelId);
        }
        
        public System.Threading.Tasks.Task<RentItMvc.RentItService.Channel> GetChannelAsync(int channelId) {
            return base.Channel.GetChannelAsync(channelId);
        }
        
        public int[] GetAllChannelIds() {
            return base.Channel.GetAllChannelIds();
        }
        
        public System.Threading.Tasks.Task<int[]> GetAllChannelIdsAsync() {
            return base.Channel.GetAllChannelIdsAsync();
        }
        
        public RentItMvc.RentItService.Channel[] GetChannels(RentItMvc.RentItService.ChannelSearchArgs args) {
            return base.Channel.GetChannels(args);
        }
        
        public System.Threading.Tasks.Task<RentItMvc.RentItService.Channel[]> GetChannelsAsync(RentItMvc.RentItService.ChannelSearchArgs args) {
            return base.Channel.GetChannelsAsync(args);
        }
        
        public void CreateVote(int rating, int userId, int trackId) {
            base.Channel.CreateVote(rating, userId, trackId);
        }
        
        public System.Threading.Tasks.Task CreateVoteAsync(int rating, int userId, int trackId) {
            return base.Channel.CreateVoteAsync(rating, userId, trackId);
        }
        
        public void AddTrack(int userId, int channelId, System.IO.MemoryStream audioStream) {
            base.Channel.AddTrack(userId, channelId, audioStream);
        }
        
        public System.Threading.Tasks.Task AddTrackAsync(int userId, int channelId, System.IO.MemoryStream audioStream) {
            return base.Channel.AddTrackAsync(userId, channelId, audioStream);
        }
        
        public RentItMvc.RentItService.Track GetTrackInfoByTrackname(int channelId, string trackname) {
            return base.Channel.GetTrackInfoByTrackname(channelId, trackname);
        }
        
        public System.Threading.Tasks.Task<RentItMvc.RentItService.Track> GetTrackInfoByTracknameAsync(int channelId, string trackname) {
            return base.Channel.GetTrackInfoByTracknameAsync(channelId, trackname);
        }
        
        public void RemoveTrack(int trackId) {
            base.Channel.RemoveTrack(trackId);
        }
        
        public System.Threading.Tasks.Task RemoveTrackAsync(int trackId) {
            return base.Channel.RemoveTrackAsync(trackId);
        }
        
        public int[] GetTrackIds(int channelId) {
            return base.Channel.GetTrackIds(channelId);
        }
        
        public System.Threading.Tasks.Task<int[]> GetTrackIdsAsync(int channelId) {
            return base.Channel.GetTrackIdsAsync(channelId);
        }
        
        public RentItMvc.RentItService.Track[] GetTracks(int channelId, RentItMvc.RentItService.TrackSearchArgs args) {
            return base.Channel.GetTracks(channelId, args);
        }
        
        public System.Threading.Tasks.Task<RentItMvc.RentItService.Track[]> GetTracksAsync(int channelId, RentItMvc.RentItService.TrackSearchArgs args) {
            return base.Channel.GetTracksAsync(channelId, args);
        }
        
        public void CreateComment(string comment, int userId, int channelId) {
            base.Channel.CreateComment(comment, userId, channelId);
        }
        
        public System.Threading.Tasks.Task CreateCommentAsync(string comment, int userId, int channelId) {
            return base.Channel.CreateCommentAsync(comment, userId, channelId);
        }
        
        public void DeleteComment(int channelId, int userId, System.DateTime date) {
            base.Channel.DeleteComment(channelId, userId, date);
        }
        
        public System.Threading.Tasks.Task DeleteCommentAsync(int channelId, int userId, System.DateTime date) {
            return base.Channel.DeleteCommentAsync(channelId, userId, date);
        }
        
        public RentItMvc.RentItService.Comment[] GetChannelComments(int channelId, System.Nullable<int> fromInclusive, System.Nullable<int> toExclusive) {
            return base.Channel.GetChannelComments(channelId, fromInclusive, toExclusive);
        }
        
        public System.Threading.Tasks.Task<RentItMvc.RentItService.Comment[]> GetChannelCommentsAsync(int channelId, System.Nullable<int> fromInclusive, System.Nullable<int> toExclusive) {
            return base.Channel.GetChannelCommentsAsync(channelId, fromInclusive, toExclusive);
        }
        
        public RentItMvc.RentItService.Comment[] GetUserComments(int userId, int fromInclusive, int toExclusive) {
            return base.Channel.GetUserComments(userId, fromInclusive, toExclusive);
        }
        
        public System.Threading.Tasks.Task<RentItMvc.RentItService.Comment[]> GetUserCommentsAsync(int userId, int fromInclusive, int toExclusive) {
            return base.Channel.GetUserCommentsAsync(userId, fromInclusive, toExclusive);
        }
        
        public bool IsEmailAvailable(string email) {
            return base.Channel.IsEmailAvailable(email);
        }
        
        public System.Threading.Tasks.Task<bool> IsEmailAvailableAsync(string email) {
            return base.Channel.IsEmailAvailableAsync(email);
        }
        
        public bool IsUsernameAvailable(string username) {
            return base.Channel.IsUsernameAvailable(username);
        }
        
        public System.Threading.Tasks.Task<bool> IsUsernameAvailableAsync(string username) {
            return base.Channel.IsUsernameAvailableAsync(username);
        }
        
        public void Subscribe(int userId, int channelId) {
            base.Channel.Subscribe(userId, channelId);
        }
        
        public System.Threading.Tasks.Task SubscribeAsync(int userId, int channelId) {
            return base.Channel.SubscribeAsync(userId, channelId);
        }
        
        public void Unsubscribe(int userId, int channelId) {
            base.Channel.Unsubscribe(userId, channelId);
        }
        
        public System.Threading.Tasks.Task UnsubscribeAsync(int userId, int channelId) {
            return base.Channel.UnsubscribeAsync(userId, channelId);
        }
        
        public int GetChannelPort(int channelId, int ipAddress, int port) {
            return base.Channel.GetChannelPort(channelId, ipAddress, port);
        }
        
        public System.Threading.Tasks.Task<int> GetChannelPortAsync(int channelId, int ipAddress, int port) {
            return base.Channel.GetChannelPortAsync(channelId, ipAddress, port);
        }
        
        public void StartChannelStream(int cId) {
            base.Channel.StartChannelStream(cId);
        }
        
        public System.Threading.Tasks.Task StartChannelStreamAsync(int cId) {
            return base.Channel.StartChannelStreamAsync(cId);
        }
        
        public RentItMvc.RentItService.ChannelSearchArgs GetDefaultChannelSearchArgs() {
            return base.Channel.GetDefaultChannelSearchArgs();
        }
        
        public System.Threading.Tasks.Task<RentItMvc.RentItService.ChannelSearchArgs> GetDefaultChannelSearchArgsAsync() {
            return base.Channel.GetDefaultChannelSearchArgsAsync();
        }
        
        public RentItMvc.RentItService.TrackSearchArgs GetDefaultTrackSearchArgs() {
            return base.Channel.GetDefaultTrackSearchArgs();
        }
        
        public System.Threading.Tasks.Task<RentItMvc.RentItService.TrackSearchArgs> GetDefaultTrackSearchArgsAsync() {
            return base.Channel.GetDefaultTrackSearchArgsAsync();
        }
        
        public RentItMvc.RentItService.Channel[] GetCreatedChannels(int userId) {
            return base.Channel.GetCreatedChannels(userId);
        }
        
        public System.Threading.Tasks.Task<RentItMvc.RentItService.Channel[]> GetCreatedChannelsAsync(int userId) {
            return base.Channel.GetCreatedChannelsAsync(userId);
        }
        
        public RentItMvc.RentItService.Channel[] GetSubscribedChannels(int userId) {
            return base.Channel.GetSubscribedChannels(userId);
        }
        
        public System.Threading.Tasks.Task<RentItMvc.RentItService.Channel[]> GetSubscribedChannelsAsync(int userId) {
            return base.Channel.GetSubscribedChannelsAsync(userId);
        }
        
        public RentItMvc.RentItService.Track[] GetTrackByChannelId(int channelId) {
            return base.Channel.GetTrackByChannelId(channelId);
        }
        
        public System.Threading.Tasks.Task<RentItMvc.RentItService.Track[]> GetTrackByChannelIdAsync(int channelId) {
            return base.Channel.GetTrackByChannelIdAsync(channelId);
        }
        
        public RentItMvc.RentItService.Track[] GetRecentlyPlayedTracks(int channelId, int numberOfTracks) {
            return base.Channel.GetRecentlyPlayedTracks(channelId, numberOfTracks);
        }
        
        public System.Threading.Tasks.Task<RentItMvc.RentItService.Track[]> GetRecentlyPlayedTracksAsync(int channelId, int numberOfTracks) {
            return base.Channel.GetRecentlyPlayedTracksAsync(channelId, numberOfTracks);
        }
        
        public bool IsChannelNameAvailable(int channelId, string channelName) {
            return base.Channel.IsChannelNameAvailable(channelId, channelName);
        }
        
        public System.Threading.Tasks.Task<bool> IsChannelNameAvailableAsync(int channelId, string channelName) {
            return base.Channel.IsChannelNameAvailableAsync(channelId, channelName);
        }
        
        public int GetSubscriberCount(int channelId) {
            return base.Channel.GetSubscriberCount(channelId);
        }
        
        public System.Threading.Tasks.Task<int> GetSubscriberCountAsync(int channelId) {
            return base.Channel.GetSubscriberCountAsync(channelId);
        }
        
        public void IncrementChannelPlays(int channelId) {
            base.Channel.IncrementChannelPlays(channelId);
        }
        
        public System.Threading.Tasks.Task IncrementChannelPlaysAsync(int channelId) {
            return base.Channel.IncrementChannelPlaysAsync(channelId);
        }
        
        public bool IsChannelPlaying(int channelId) {
            return base.Channel.IsChannelPlaying(channelId);
        }
        
        public System.Threading.Tasks.Task<bool> IsChannelPlayingAsync(int channelId) {
            return base.Channel.IsChannelPlayingAsync(channelId);
        }
        
        public void StopChannelStream(int channelId) {
            base.Channel.StopChannelStream(channelId);
        }
        
        public System.Threading.Tasks.Task StopChannelStreamAsync(int channelId) {
            return base.Channel.StopChannelStreamAsync(channelId);
        }
        
        public RentItMvc.RentItService.Vote GetVote(int userId, int trackId) {
            return base.Channel.GetVote(userId, trackId);
        }
        
        public System.Threading.Tasks.Task<RentItMvc.RentItService.Vote> GetVoteAsync(int userId, int trackId) {
            return base.Channel.GetVoteAsync(userId, trackId);
        }
        
        public void DeleteVote(int userId, int trackId) {
            base.Channel.DeleteVote(userId, trackId);
        }
        
        public System.Threading.Tasks.Task DeleteVoteAsync(int userId, int trackId) {
            return base.Channel.DeleteVoteAsync(userId, trackId);
        }
        
        public int CountAllChannelsWithFilter(RentItMvc.RentItService.ChannelSearchArgs filter) {
            return base.Channel.CountAllChannelsWithFilter(filter);
        }
        
        public System.Threading.Tasks.Task<int> CountAllChannelsWithFilterAsync(RentItMvc.RentItService.ChannelSearchArgs filter) {
            return base.Channel.CountAllChannelsWithFilterAsync(filter);
        }
    }
}
