//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentItServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class channels
    {
        public channels()
        {
            this.comments = new HashSet<comments>();
            this.tracks = new HashSet<tracks>();
            this.genres = new HashSet<genres>();
            this.users1 = new HashSet<users>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<double> rating { get; set; }
        public Nullable<int> plays { get; set; }
        public string description { get; set; }
        public int userId { get; set; }
    
        public virtual users users { get; set; }
        public virtual ICollection<comments> comments { get; set; }
        public virtual ICollection<tracks> tracks { get; set; }
        public virtual ICollection<genres> genres { get; set; }
        public virtual ICollection<users> users1 { get; set; }
    }
}
