//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentItServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class comments
    {
        public int channelId { get; set; }
        public int userId { get; set; }
        public string content { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual channels channels { get; set; }
        public virtual users users { get; set; }
    }
}
