//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentItServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class genres
    {
        public genres()
        {
            this.channels = new HashSet<channels>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<channels> channels { get; set; }
    }
}
